services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - rust_kafka_kafka-net
    
  dbt_weather:
    container_name: dbt_weather
    build:
      context: .
    environment:
      - DBT_TARGET=prod
      - DBT_PROFILES_DIR=/root/.dbt
    volumes:
      - .:/usr/app
      - ./profiles.yml:/root/.dbt/profiles.yml
      - ./target:/usr/app/target
    tty: true
    stdin_open: true
    networks:
      - rust_kafka_kafka-net
    
volumes:
  grafana-storage:

networks:
  rust_kafka_kafka-net:
    external: true