dbt_weather:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      host: "{{ env_var('DBT_DEV_HOST') }}"
      user: "{{ env_var('DBT_DEV_USER') }}"
      password: "{{ env_var('DBT_DEV_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DEV_NAME') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
    
    prod:
      host: "{{ env_var('DBT_PROD_HOST') }}"
      user: "{{ env_var('DBT_PROD_USER') }}"
      password: "{{ env_var('DBT_PROD_PASSWORD') }}"
      dbname: "{{ env_var('DBT_PROD_NAME') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
