[project]
name = "dbt-weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.10.2",
    "dbt-postgres>=1.9.0",
]
